language: java

services:
  - docker

sudo: required
git:
  depth: 3

before_install:
  - sudo /etc/init.d/mysql stop
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly

install:
  - git clone https://github.com/FAForever/faf-stack.git
  - docker-compose -f faf-stack/docker-compose.yml up -d faf-db

script:
  - chmod +x gradlew && ./gradlew build --info

after_success:
  - ./gradlew jacocoTestReport coveralls
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then
      ./gradlew pushDockerImage;
    fi
  - ~/jpm/bin/codacy-coverage-reporter -l Java -r build/reports/jacoco/test/jacocoTestReport.xml

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
