language: java

services:
  - docker

sudo: required
git:
  depth: 3

before_install:
  - sudo /etc/init.d/mysql stop

install:
  - git clone https://github.com/FAForever/db.git
  - pushd db && ./setup_db.sh && popd

script:
  - chmod +x gradlew && ./gradlew build --info

after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then
      ./gradlew jacocoTestReport coveralls pushDockerImage;
    fi

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
