spring:
  jackson:
      serialization.indent_output: true
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS:localhost}/${DATABASE_NAME:faf}?useSSL=false
    name: faf-db
    username: ${DATABASE_USERNAME:faf-server}
    password: ${DATABASE_PASSWORD:banana}
  jpa:
    show-sql: false
  boot:
    admin:
      url: ${SPRING_BOOT_ADMIN_URL:http://localhost:8030}
      client:
        enabled: ${SPRING_BOOT_ADMIN_ENABLED:false}

faf-server:
  uid:
    enabled: ${UID_ENABLED:false}
  geo-ip:
    database-file: ${GEO_IP_DB_FILE:build/cache/geoIp.mmdb}
  api:
    base-url: ${API_BASE_URL:http://localhost:8010}
    client-id: ${API_CLIENT_ID:faf-server}
    client-secret: ${API_CLIENT_SECRET:banana}
    access-token-uri: ${API_ACCESS_TOKEN_URI:http://localhost:8010/oauth/token}
  jwt:
    secret: ${JWT_SECRET:banana}

logging:
  level:
    com.faforever.server: warn
