spring:
  jackson:
      serialization.indent_output: true
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS:localhost}/${DATABASE_NAME:faf_test}?useSSL=false
    name: faf-db
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:banana}
  jpa:
    show-sql: true

logging:
  level:
    com.faforever.server: trace

security:
  oauth2:
    client:
      clientId: faf-server
      clientSecret: banana
      accessTokenUri: ${API_OAUTH2_ACCESS_TOKEN_URI:http://localhost:8080/oauth/token}
      userAuthorizationUri: ${API_OAUTH2_AUTHORIZATION_URI:http://localhost:8080/oauth/authorize}

faf-server:
  uid:
    enabled: false





