faf-server:
  version:
  true-skill:
    initial-mean: 1500
    initial-standard-deviation: 500
    beta: 240
    dynamic-factor: 10
    draw-probability: 0.1


spring:
  application:
    name: FAF Java Server Prototype
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 2
      maximum-pool-size: 8
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: ${SERVER_PROFILE:dev}
  main:
    banner-mode: off

logging:
  level:
    org.springframework: warn
    com.faforever.server: info
    com.zaxxer.hikari: warn
    org.hibernate: warn
    org.eclipse.jetty: warn

security:
  oauth2:
    client:
      clientAuthenticationScheme: header
