spring:
  jackson:
      serialization.indent_output: true
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS:localhost}/${DATABASE_NAME:faf_test}?useSSL=false
    name: faf-db
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:banana}
  jpa:
    show-sql: true

logging:
  level:
    org.springframework: warn
    com.faforever.server: trace

