spring:
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS}/${DATABASE_NAME}?useSSL=false
    name: faf-db
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false

security:
  oauth2:
    client:
      clientId: ${API_OAUTH2_CLIENT_ID}
      clientSecret: ${API_OAUTH2_CLIENT_SECRET}
      accessTokenUri: ${API_OAUTH2_ACCESS_TOKEN_URI:https://japi.faforever.com/oauth/token}
      userAuthorizationUri: ${API_OAUTH2_AUTHORIZATION_URI:https://japi.faforever.com/oauth/authorize}
