spring:
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS}/${DATABASE_NAME}?useSSL=false
    name: faf-db
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
  boot:
    admin:
      url: ${SPRING_BOOT_ADMIN_URL:http://faf-spring-boot-admin:8030}

faf-server:
  uid:
    enabled: true
    private-key: ${UID_PRIVATE_KEY}
    link-to-steam-url: ${STEAM_LINK_URL:http://app.faforever.com/faf/steam.php}
